### PR TITLE
add control scripts for LSF in Aaditya

### PR DESCRIPTION
**Pull request by cd10kfsu**
1. Add control scripts for LSF in Aaditya: lsf_cycle, lsf.py
2. Add configurations and env for compiling CFSv2-LETKF in Aaditya
3. Add the option to disable TMP_DIR_LOCAL in control scripts
4. Remove software-dependent sentence from the controlling scripts
5. Add script that helps to set up a new experiment from the output of another experiment: init_copy

### CODE REVIEW

**Review by travissluka — APPROVED** [review]

**Comment by travissluka** [comment]
@cd10kfsu  I went ahead and approved so that you can merge this in.

If you could request a review (button on the top right) from someone who has the ability to test on aaditya, that would be great. Otherwise, you should have permissions now to merge this PR yourself.

**Comment by cd10kfsu** [comment]
I will ask Kriti's help to test it on Aaditya. After she finishes the test and finds no problem, I will then merge the branch. Thank you!

**Comment by kbhargava** [comment]
Will do!

**Review by kbhargava — APPROVED** [review]

**Review by kbhargava — APPROVED** [review]

**Comment by cd10kfsu** [comment]
thanks! @kbhargava

**Pull request merged**
